# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e19ce528cf9bcd6b7f434dbcece3cd1278fdff0a58616a67eae8c3f064e2bf42e3e0a83f14d1107a2d7679e2caf519bfcce6004e713b417fb03da2f3e1554485

test:
  secret_key_base: 303f77d86275a258d157e44efaa34f5acbc03940fc145a04fb8680ad4034532026aacfa71987a361ca6dd40cbaebc0acdfc5a135266a9a8f447d4d6c36c64b9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
